# Generated by Django 3.0.6 on 2020-05-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200506_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
