# Generated by Django 3.0.6 on 2020-05-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200506_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
